## [Inversion Counting Problem](https://www.spoj.com/problems/INVCNT/)

- Status: Error submission :x:
- Type error: `"terminate called after throwing an instance of 'std::bad_alloc'
                   what():  std::bad_alloc"`
                   
 
Solved | Solution | Time :clock11: | 
--- | --- | --- | 
:x: | :x: | :x: